spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.coyoapp.tinytask: DEBUG

mail:
  default-encoding: UTF-8
  host: smtp.gmail.com
  username: <Gmail username>
  password: <Gmail password>
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  protocol: smtp
  test-connection: false
